name: On pull request push

on:
  pull_request:
    branches:
        - "*"

jobs:
  tests:
    name: Run test suites
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: pip install .[dev]

      - name: Run unit tests
        env:
          TEST_FOLDER: tests
        run: pytest  tests/test_token_fetcher_cli.py  --service_username "serv_user" 
          --service_password "serv_pass" --regular_username "reg_user" 
          --regular_password "reg_pass"  --color yes
